# Generated by Django 4.1.7 on 2023-03-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paidusers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('sum', models.FloatField(blank=True, null=True)),
                ('succesed', models.BooleanField(default=False)),
            ],
        ),
    ]
