# Generated by Django 4.1.7 on 2023-03-21 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_contact_contactgroup_rename_sum_paidusers_total_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pay.contactgroup'),
        ),
    ]
