# Generated by Django 4.1.7 on 2023-03-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_contact_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='contact',
            field=models.ManyToManyField(blank=True, to='pay.contactdata'),
        ),
    ]
