# Generated by Django 4.1.7 on 2023-03-22 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0004_contactdata_delete_contact_contactgroup_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactgroup',
            name='contact',
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pay.contactdata'),
        ),
    ]
