# Generated by Django 4.1.7 on 2023-03-22 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0005_remove_contactgroup_contact_contactgroup_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactGroup',
        ),
    ]
