# Generated by Django 4.1.7 on 2023-03-22 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0006_delete_contactgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdata',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pay.contactdata'),
        ),
        migrations.AddField(
            model_name='contactdata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='contactdata',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contactdata',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
