# Generated by Django 4.1.7 on 2023-03-22 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0007_contactdata_contact_contactdata_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdata',
            name='contact',
        ),
    ]
