# Generated by Django 4.1.4 on 2023-04-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0008_remove_contactdata_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidusers',
            name='discord_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
